# Generated by Django 2.0 on 2017-12-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
