# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl', models.CharField(max_length=64)),
                ('uk', models.CharField(max_length=64)),
                ('transcript', models.CharField(max_length=64)),
                ('related_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polish.Lesson')),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
