# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polish', '0002_auto_20171210_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=32)),
                ('related_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polish.Lesson')),
            ],
        ),
    ]
