# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polish', '0004_auto_20171210_1845'),
        ('polish', '0002_auto_20171210_0001'),
    ]

    operations = [
    ]
