# Generated by Django 2.0 on 2017-12-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polish', '0006_auto_20171212_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Урок', max_length=32),
        ),
    ]
